### ISSUE TITLE
InputEvent not fired on views from viewpool

### ISSUE THREAD

**Issue by jestillore** [gameclosure/devkit2#99]
Btw, I am using ParallaxView.js from the sample game Platformer.
I have an image view taken from the viewpool via ```layer.obtainView(ImageView)```,updated it's properties, and assigning ```layer``` variable as its parent view.
But when I tried to listen for ```InputStart``` event from the view, it would not fire. Strange that when I change its parent view to another view, not the layer it would fire the event.
Below is my code:
```
var heart = layer.obtainView(ImageView, {
	x: x,
	y: y < 50 ? y : y - 50,
	width: 50,
	height: 50,
	anchorX: 25,
	anchorY: 25,
	r: d2r(90),
	image: image,
	superview: layer
});
heart.on('InputStart', bind(this, function () {
	console.log('yeah');
}));
```

**Comment by jwilm** [comment]
@rogueSkib can you take a look?

**Comment by rogueSkib** [comment]
My guess would be that the parallax layer is a moving view, and the heart you're trying to tap is not within the bounds of that layer. Typically, parallax classes don't support input, but you could try making the superview infinite so that any subviews accept input, regardless of their parents bounds.

If you want a more powerful and supported parallax system, check out this devkit2 module I created: https://github.com/gameclosure/devkit-parallax

**Comment by rogueSkib** [comment]
Here's the code and comments around making an instance of View infinite:
https://github.com/gameclosure/timestep/blob/master/src/ui/View.js#L124
